apiVersion: v1
kind: Secret
metadata:
    name: secret-demo
stringData:
    .env: ENC[AES256_GCM,data:IInVgaNtH9IwyEWddBub4yIH8Lpnkc+rUasyVKJyjuLO5plreM6rQUnc0hegbIUAPno6yB6JHpTwAiToCDQj,iv:p7esBai3D1gpUGrqJ34cUTViFLZ4mBc9plWbTzOrZ74=,tag:he2KXUCbDs4rPLVcTwZokQ==,type:str]
sops:
    age:
        - recipient: age15hjwnavjq8z2fplj3yjgpa58xcxly76ksadt0xvea2phtszmte7s47lvxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWblpPaURvSTBJbGVYUkh3
            aFZ4a0x5S3oxKzlHUFY0V0NzQ1ZFU1ZwYXp3CjlMTTIrRnZ3dEdOdU5SQW9kYjRZ
            MW5xaUk2ckpUcnlDTGJSRlZidEYrY2MKLS0tIHpyTm43d0tIMXd5ZUQxSUo5WUV6
            RjdEcjd0Sy9NdmpRbTI2azZ1UVZFOEEKWKf8FepUwv3YmmFnIQ4gENfafU9cmR1h
            or6xU3S4NcmV9EQw20M+e8cVB75HO1VUGqJJAsXkmAG7ZJQtEJYLyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T09:24:40Z"
    mac: ENC[AES256_GCM,data:dEyPJrqKBdmEuxFemiFEaq7fNDEm8fWkiIWFoAILVxv0c8Fl3TjezMtNGO9TG3bJ9zqRg1ZFGXtqihVrwp7I4B+q8B50oa8XRQ3fNy8JZgPajllRCWxNKBG9hjY9uTgG3EFIiDxl+kOvb6WLTBuJqlwL/I+Skm7Tw0tL+U4l+38=,iv:RMZdulBK5TAjeCR28SgxapqBFfHDLW+Zm+YDHJf4UIM=,tag:SkHXhll/t8OqjIN6Tcb5qQ==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.12.1
