apiVersion: v1
kind: Secret
metadata:
    name: secret-demo
    namespace: default
stringData:
    .env: ENC[AES256_GCM,data:MPXf520PyEMACtFyu5Z6buPskqRVnZ8Vfu0zX3R2KeiGGH4LIZuHQ7Kqz+Unl8EhA7jes0ygJno+ifmhn/+n,iv:LGZUW7G1XOeGOL26PCaQaYPtN7PwE1TB+OrImgBpg70=,tag:lqgPABU/UoY5F572fNNdRg==,type:str]
sops:
    age:
        - recipient: age13h4xgfmmd9m96yxj7uy9f9ztawxvkcy85c86yv2lufzhugp2yplstm2mfg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ0V1WGxrRGc4RG8yZ0FG
            Ujlqb1RKaUYzZHhsa0ZWcG9DVUtjaU9zcHd3CmJWdGI5WE1NYVFkV3pHVzN0RU9W
            ejJWdEp5VEdlSm55RzNSQ3J6QzFyTEEKLS0tIHVMUmZxOVZHRjBJZ2ROcHJmOUFn
            RlRMVHBhb2VZZTYxV2owUGdnZXg5eFkKOsGqgaiHK1krzgNC498y5yQ0QMybqm2k
            zNmKt68Y1Y6ZAOifWIC8c1CBCMJ/ICOn2zF7xhFpHOfl+QjuPQSKgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T13:49:33Z"
    mac: ENC[AES256_GCM,data:tDiRDbXM8cTj7rubcqUDrx4X/l7rOUyjvrPd9b17NrLxZQOA/4e72a13kayL6oJ3Wu7P5QV+xQ6t6XzX+rKjGZzhZZa2kEwGMbv4sNen1vUk6Gf73o13ISOtNR3dLKEE5S+ZD5swS4bprD0gB/bkB7KTrlQ+0znG0PlxKPsl/Fk=,iv:DxE8CnOiSx+IeFTOcKqZapyRX1o+zuGztIHdn0TmAyM=,tag:rqK8z3QSI8mvrahLzMMWYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
