apiVersion: v1
kind: Secret
metadata:
    name: secret-demo
stringData:
    .env: ENC[AES256_GCM,data:pEOMgSPUjVgs+PtZdYPM66PRSLsdOW/Hbg7LoqCW4voRdCWMlA9hqxNdN+F8Yzpqyzr3Qpi5QzXmnYEY1DQz,iv:WVxPqF5mTIEAPKU8ee6iVFkvWVVXWSMj9xe0QWUbshU=,tag:bslbEX8CLh0G4pmDTgSaFg==,type:str]
sops:
    age:
        - recipient: age13h4xgfmmd9m96yxj7uy9f9ztawxvkcy85c86yv2lufzhugp2yplstm2mfg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeHdrYWVlbGFQUUluckVT
            cjdiTmdsUXB2cFJqMXJPTmlhUzVwNGgvVkFJCi9DdkVGWkJ2R253SGY2ZUFCOW1S
            NVZqemFNQ1VPNlN6U3RiejNxdks3ODgKLS0tIDU1a2hvdnJGMUhia2puQ202YXRU
            TkdHNVJaT3oybnBGMExaUmhGOStDaTAKGj0wp0sCTYsaCzdh4/F9YiBJyuYlb1S+
            7YHcHfdH3O7cucAaztITU9VnvuQwYG96k+4iLmaf/QP1WHASNO2NNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T13:32:03Z"
    mac: ENC[AES256_GCM,data:LTYdldBO/qikFxUEtj5/UxtssihbECJ0rMnq8Xd9A8DnPWURK9OLnNmhw32S9Jp+xGcaFscndtrJ1+WhWWahEo0BUwoblEaIsbCQcsHKeuBE0crKw1vLCjqQOGDKDBSGXsUAV5Yzoa2BtlQAV/trIygwAWswb1gqVIyncYT6qRg=,iv:ziSTrgcEHx2dfL3EiNBqyUQmC7b/AGk4bAa8tlgnCDE=,tag:QMI7E3HmpqWdoa8816UlBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
