apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-nginx
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: test-nginx
    template:
        metadata:
            labels:
                app: test-nginx
        spec:
            containers:
                - name: nginx
                  image: nginx:alpine
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: env-volume
                        mountPath: /.env
                        subPath: .env
                        readOnly: true
            volumes:
                - name: env-volume
                  projected:
                      sources:
                          - secret:
                                name: secret-demo
                                items:
                                    - key: .env
                                      path: .env
